# Generated by Django 4.2.2 on 2023-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
