# Generated by Django 4.2.2 on 2023-08-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_rename_month_challenges_month_name_alter_months_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='month_name',
        ),
        migrations.AddField(
            model_name='challenges',
            name='months',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='challenges.months'),
        ),
    ]
