# Generated by Django 4.2.2 on 2023-08-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_remove_challenges_month_name_challenges_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='months',
        ),
        migrations.AddField(
            model_name='months',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenges'),
        ),
    ]
