# Generated by Django 4.2.2 on 2023-08-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_challenges_challenge_remove_months_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
    ]
