# Generated by Django 4.2.2 on 2023-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_alter_months_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
