# Generated by Django 4.2.2 on 2023-08-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_months_cchallengee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months',
            name='challenge',
        ),
        migrations.AddField(
            model_name='months',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenges'),
        ),
    ]
