# Generated by Django 4.2.2 on 2023-08-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_remove_months_challenge_months_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months',
            name='cchallengee',
        ),
        migrations.AlterField(
            model_name='months',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
